set nocompatible
    
if has('filetype')
  filetype indent plugin on
endif

if has('syntax')
  syntax on
endif

set wildmenu
set showcmd
set hlsearch
set hidden

set ignorecase
set smartcase

set backspace=indent,eol,start

set autoindent
set shiftwidth=4
set softtabstop=4
set smarttab
set nostartofline

set ruler

set laststatus=2

set confirm

set visualbell

set number
set cursorline
set autoindent

colorscheme badwolf
